services:
  db:
    image: postgres:16
    container_name: task_mgmt_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_mgmt_db
    ports:
      - "54334:5432"
    volumes:
      - task_mgmt_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_mgmt_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: task_mgmt_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/task_mgmt_db
      - SECRET_KEY=supersecretjwtkeyforinterviewtesttask12345
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    depends_on:
      db:
        condition: service_healthy

volumes:
  task_mgmt_data:
