"""remove_gemini_api_key

Revision ID: b6b3046887cf
Revises: 3e7a46cfda0b
Create Date: 2026-08-20 15:15:19.598333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b3046887cf'
down_revision: Union[str, Sequence[str], None] = '3e7a46cfda0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
